#PBS -l select=1:ncpus=10:ngpus=1
#PBS -P CSCI1335
#PBS -q gpu_1
#PBS -o /mnt/lustre3p/users/ynurmahomed/dan-tune/out
#PBS -e /mnt/lustre3p/users/ynurmahomed/dan-tune/err
#PBS -l walltime=00:50:00
#PBS -WMail_Users=nrmyas001@myuct.ac.za

module load chpc/python/3.7.0
cd /mnt/lustre3p/users/ynurmahomed/clinical-longformer
source .venv/bin/activate

ipython -m src.clinical_longformer.tune.dan -- \
    /mnt/lustre3p/users/ynurmahomed/datasets/discharge/-1 \
    --vectors_root=/mnt/lustre3p/users/ynurmahomed/.data \
    --local_dir=/mnt/lustre3p/users/ynurmahomed/ray_results \
    --num_samples=100 \
    --max_epochs=10 \
    --num_workers=6 \
    --gpus=1
