#PBS -l select=1:ncpus=10:ngpus=1
#PBS -P CSCI1335
#PBS -q gpu_1
#PBS -o /mnt/lustre3p/users/ynurmahomed/logs/lstm-tune/
#PBS -e /mnt/lustre3p/users/ynurmahomed/logs/lstm-tune/
#PBS -l walltime=07:00:00
#PBS -WMail_Users=nrmyas001@myuct.ac.za

module load chpc/python/3.7.0
cd /mnt/lustre3p/users/ynurmahomed/clinical-longformer
source .venv/bin/activate

ipython -m src.clinical_longformer.tune.lstm -- \
    /mnt/lustre3p/users/ynurmahomed/datasets/discharge/-1 \
    --vectors_root=/mnt/lustre3p/users/ynurmahomed/.data \
    --local_dir=/mnt/lustre3p/users/ynurmahomed/ray_results \
    --num_samples=100 \
    --max_epochs=2 \
    --log_every_n_steps=25
    --val_check_interval=25
    --num_workers=6 \
    --gpus=1
