#!/bin/sh
#SBATCH --account=nlpgroup --partition=a100
#SBATCH --nodes=1 --ntasks=6
#SBATCH --gres=gpu:a100-2g-10gb:1
#SBATCH --job-name="bert-test"
#SBATCH --mail-user=nrmyas001@cs.uct.ac.za
#SBATCH --mail-type=ALL
#SBATCH --time=00:10:00

module load software/TensorFlow-A100-GPU

export CUDA_VISIBLE_DEVICES=$(ncvd)
export TOKENIZERS_PARALLELISM=false
export WANDB_DIR=/scratch/nrmyas001
export WANDB_ENTITY=yass
export WANDB_PROJECT=clinical-longformer-test
export WANDB_NAME=BERT

cd /home/nrmyas001/clinical-longformer-test

python -m src.clinical_longformer.model.bert  \
    /scratch/nrmyas001/datasets/discharge/512 \
    --do_test \
    --bert_pretrained_path=/scratch/nrmyas001/data/pretraining_output/bert_uncased_L-12_H-768_A-12/512/ \
    --resume_from_checkpoint=/scratch/nrmyas001/data/model/BERT/AVG-Precision_valid=0.69-epoch=5-step=2788.ckpt \
    --num_workers=6 \
    --precision=16 \
    --gpus=1 2>&1 | tee /scratch/nrmyas001/logs/bert-test/$(hostname)$(openssl rand -hex 4).out
