#!/bin/sh
#SBATCH --account=nlpgroup --partition=a100
#SBATCH --nodes=1 --ntasks=6
#SBATCH --gres=gpu:ampere:1
#SBATCH --job-name="longf-2048-test"
#SBATCH --mail-user=nrmyas001@myuct.ac.za
#SBATCH --mail-type=END,FAIL
#SBATCH --time=00:10:00

module load software/TensorFlow-A100-GPU

export CUDA_VISIBLE_DEVICES=$(ncvd)
export TOKENIZERS_PARALLELISM=false
export WANDB_DIR=/scratch/nrmyas001
export WANDB_ENTITY=yass
export WANDB_PROJECT=clinical-longformer-test

cd /home/nrmyas001/clinical-longformer-test

for ckpt in $(ls /scratch/nrmyas001/data/model/Longformer-2048/AVG-Precision_valid=0.62-epoch=0-step=165.ckpt);
do
  python -m src.clinical_longformer.model.longformer \
      /scratch/nrmyas001/datasets/discharge/2048 \
      --do_test \
      --bert_pretrained_path=/scratch/nrmyas001/data/pretraining_output/v2/bert_uncased_L-12_H-768_A-12-2048/2048/ \
      --resume_from_checkpoint=$ckpt \
      --attention_window=1024 \
      --max_length=2048 \
      --run_name=Longformer-2048 \
      --num_workers=6 \
      --precision=16 \
      --gpus=1 2>&1 | tee /scratch/nrmyas001/logs/longf-test/$(hostname)$(openssl rand -hex 4).out
done
