#!/bin/sh
#SBATCH --account=nlpgroup --partition=a100
#SBATCH --nodes=1 --ntasks=6
#SBATCH --gres=gpu:a100-1g-5gb:1
#SBATCH --job-name="lstm-early-test"
#SBATCH --mail-user=nrmyas001@myuct.ac.za
#SBATCH --mail-type=END,FAIL
#SBATCH --time=00:30:00

module load software/TensorFlow-A100-GPU

export CUDA_VISIBLE_DEVICES=$(ncvd)
export TOKENIZERS_PARALLELISM=false
export WANDB_DIR=/scratch/nrmyas001
export WANDB_ENTITY=yass
export WANDB_PROJECT=clinical-longformer-early-test



cd /home/nrmyas001/clinical-longformer

for n in 1 2 3 4 5 6 7
do
export WANDB_NAME=LSTM-$n-days
python -m src.clinical_longformer.model.lstm \
    /scratch/nrmyas001/datasets/all7days/all/-1/${n}days/ \
    --do_test \
    --vectors_root=/scratch/nrmyas001/data \
    --resume_from_checkpoint=/scratch/nrmyas001/data/model/LSTM-early/AVG-Precision_valid=0.61-epoch=1-step=2383.ckpt \
    --num_workers=6 \
    --precision=16 \
    --gpus=1 2>&1 | tee /scratch/nrmyas001/logs/longf-test/$(hostname)$(openssl rand -hex 4).out
done
