#!/bin/sh
#SBATCH --account=nlpgroup --partition=a100
#SBATCH --nodes=1 --ntasks=6
#SBATCH --gres=gpu:a100-1g-5gb:1
#SBATCH --job-name="lstm-test"
#SBATCH --mail-user=nrmyas001@cs.uct.ac.za
#SBATCH --mail-type=ALL
#SBATCH --time=00:01:00

module load software/TensorFlow-A100-GPU

export CUDA_VISIBLE_DEVICES=$(ncvd)
export WANDB_DIR=/scratch/nrmyas001/wandb
export WANDB_ENTITY=yass
export WANDB_PROJECT=clinical-longformer-test
export WANDB_NAME=LSTM

python -m src.clinical_longformer.model.lstm  \
    /scratch/nrmyas001/datasets/discharge/-1 \
    --do_test \
    --embed_dim=300 \
    --hidden_dim=200 \
    --resume_from_checkpoint=/scratch/nrmyas001/data/model/LSTM/AVG-Precision_valid=0.68-epoch=8-step=557.ckpt \
    --vectors_root=/scratch/nrmyas001/data \
    --num_workers=6 \
    --precision=16 \
    --gpus=1 2>&1 | tee /scratch/nrmyas001/logs/lstm-test/$(hostname)$(openssl rand -hex 4).out
